[package]
name = "untfo-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
hex = "0.4"
md5 = "0"
aes = "0.7"
block-modes = "0.8"